// src/pipeline/lipsync.js
import { startTimer } from '../utils/timer.js';

// Simple text-to-viseme mapping rule index
const VISEME_RULES = {
    a: 'aa', e: 'E', i: 'I', o: 'O', u: 'U',
    p: 'PP', b: 'PP', m: 'PP',
    f: 'FF', v: 'FF',
    t: 'DD', d: 'DD', s: 'SS', z: 'SS',
    c: 'CH', ch: 'CH', j: 'CH', sh: 'CH',
    k: 'kk', g: 'kk', q: 'kk',
    r: 'RR', l: 'nn', n: 'nn'
};

/**
 * Generates frontend timeline instructions tracking targeted ARKit avatar mouth shape blendweights
 * @param {string} text - Clean dialogue string generated by the LLM
 * @returns {Object} An object containing the viseme array and generation time metrics
 */
export const generateVisemesFromText = (text) => {
    const timer = startTimer();
    const cleanText = text.toLowerCase().trim().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "");
    const words = cleanText.split(/\s+/);

    const visemes = [];
    let currentTimelineMs = 0;

    // Rule-of-thumb conversational pacing defaults:
    // ~140ms per syllable base, ~50ms transition intervals
    words.forEach((word) => {
        if (!word) return;

        // Break word down to simple linear characters for basic phonetic heuristic positioning
        for (let i = 0; i < word.length; i++) {
            const char = word[i];
            const nextChar = word[i + 1] || '';

            let targetViseme = 'sil';
            let duration = 65; // Time allocation window for single shape processing

            // Multi-character token fallback
            if (char === 'c' && nextChar === 'h') {
                targetViseme = VISEME_RULES['ch'];
                duration = 100;
                i++;
            } else if (VISEME_RULES[char]) {
                targetViseme = VISEME_RULES[char];
            }

            // Generate frame entry instructions
            if (targetViseme !== 'sil') {
                visemes.push({
                    time_ms: currentTimelineMs,
                    viseme: targetViseme,
                    weight: parseFloat((0.7 + Math.random() * 0.3).toFixed(2)) // Introduce mild natural organic flutter
                });
                currentTimelineMs += duration;
            }
        }

        // Add a small spacer rest window separating distinct conversational phrase words
        visemes.push({ time_ms: currentTimelineMs, viseme: 'sil', weight: 0.0 });
        currentTimelineMs += 45;
    });

    return {
        visemes,
        duration_ms: currentTimelineMs,
        processing_time_ms: timer.stop()
    };
};